import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="Ollivanders Flask",
    version="0.1.0",
    author="MatiasAgomezJ",
    author_email="matutecito@gmail.com",
    description="Small project with flask and flask restful",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/MatiasAGomezJ/ollivanders-flask.git",
    packages=setuptools.find_packages(),
    include_package_data=True,
    classifiers=[
        "Programming Language :: Python :: 3",
    ],
    python_requires=">=3.6",
    install_requires=[
        "aniso8601==9.0.1",
        "click==8.1.2",
        "colorama==0.4.4",
        "dnspython==2.2.1",
        "flask==2.0.3",
        "flask-restful==0.3.9",
        "itsdangerous==2.1.2",
        "jinja2==3.1.1",
        "markupsafe==2.1.1",
        "mongoengine==0.24.0",
        "pymongo[srv]==4.0",
        "pytz==2022.1",
        "six==1.16.0",
        "werkzeug==2.1.1",
        "atomicwrites==1.4.0",
        "attrs==21.4.0",
        "bandit==1.7.4",
        "black==22.3.0",
        "click==8.1.2",
        "colorama==0.4.4",
        "coverage==6.3.2",
        "distlib==0.3.4",
        "filelock==3.6.0",
        "gitdb==4.0.9",
        "gitpython==3.1.27",
        "iniconfig==1.1.1",
        "mypy-extensions==0.4.3",
        "packaging==21.3",
        "pathspec==0.9.0",
        "pbr==5.8.1",
        "platformdirs==2.5.1",
        "pluggy==1.0.0",
        "py==1.11.0",
        "pyparsing==3.0.8",
        "pytest==7.1.1",
        "pyyaml==6.0",
        "six==1.16.0",
        "smmap==5.0.0",
        "stevedore==3.5.0",
        "toml==0.10.2",
        "tomli==2.0.1",
        "tox==3.24.5",
        "virtualenv==20.14.0",
    ],
)
